# The initial duration of any auction
auctiontime: 900
# The delay after which an auction reminder is broadcast
reminderinterval: 60
# The minimum delay between two messages
spamprotection: 5
# The minimal amount a player has to raise for
minincrement: 5
# The maximal amount of stored future auctions
maxqueue: 1
# The maximal amount of stored past auctions
maxhistory: 20
# The language file to use
lang: en_US
# The starting bid of any auction
startingbid: 10
# A flat fee for starting an auction
auctionfee: 0
# The percentage of the additional starting price an auctioneer has to pay
auctiontax: 0
# Prevent players from starting auctions while in creative mode
denycreative: false
# Herochat configuration
herochat:
        enable: false
        channel: Trade
        password: ''
# ChannelChat configuration
channelchat:
        enable: false
        channel: Trade
# Colors
colors:
        default: dark_aqua
        header: yellow
        highlight: aqua
        shadow: dark_gray
        shortcut: white
        admin: dark_red
        adminhighlight: red
        error: dark_red
        warn: red