# The initial duration of any auction
auctiontime: 600
# The delay after which an auction reminder is broadcast
reminderinterval: 120
# The minimum delay between two messages
spamprotection: 3
# The minimal amount a player has to raise for
minincrement: 5
# The maximal amount of stored future auctions
maxqueue: 1
# The maximal amount of stored past auctions
maxhistory: 10
# The language file to use
lang: en_US
# The starting bid of any auction
startingbid: 10
# A flat fee for starting an auction
auctionfee: 0
# The percentage of the additional starting price an auctioneer has to pay
auctiontax: 0
# The time a player has to wait between starting two auctions
auctioneercooldown: 30
# Prevent players from starting auctions while in creative mode
denycreative: true
# The final seconds at which the countdown is broadcast in chat
countdown: [10, 5, 3, 2, 1]
# A list of worlds where CraftBay cannot be used
blacklistworlds: []
# DefaultChat configuration
defaultchat:
        # false means players listen by default, true means they don't and have to use /auc listen first
        whitelisted: false
# Herochat configuration
herochat:
        enable: false
        channel: Trade
        password: ''
# ChannelChat configuration
channelchat:
        enable: false
        channel: Trade
# Colors
colors:
        default: dark_aqua
        header: yellow
        highlight: aqua
        shadow: dark_gray
        shortcut: white
        admin: dark_red
        adminhigh: red
        error: dark_red
        warn: red
        warnhigh: dark_red